# Generated by Django 4.1.7 on 2024-02-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('warranty_length', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1, help_text='0 - Nieaktywny, 1 - Aktywny')),
            ],
        ),
    ]
