# Generated by Django 4.1.7 on 2024-02-25 18:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('asystent_gwarancji', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='date',
            new_name='date_purchase',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='warranty_length',
            new_name='lenght_of_warranty',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='category',
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_warranty_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='static/media'),
        ),
    ]
