# Generated by Django 4.1.7 on 2024-02-25 19:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('asystent_gwarancji', '0002_rename_date_receipt_date_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='asystent_gwarancji/static/media'),
        ),
    ]
