# Generated by Django 4.1.7 on 2024-02-25 21:01

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('asystent_gwarancji', '0003_alter_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_warranty_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='asystent_gwarancji/static/media'),
        ),
    ]
