# Generated by Django 4.1.7 on 2024-02-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asystent_gwarancji', '0004_alter_receipt_date_warranty_to_alter_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_warranty_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
